project:
  type: website
  resources:
    - main.js
    - scenes/
    - assets/

website:
  title: "Lance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: darkly
    toc: false
