project:
  type: website
  output-dir: docs
  resources:
    - main.js
    - scenes/
    - assets/

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: darkly
    toc: false
